-- SQLite schema will be added here
-- Donor Table 
CREATE TABLE donors (
    id INTEGER PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    title TEXT,
    dob DATE,
    dod DATE,
    cause_of_death TEXT,
    gender TEXT,
    occupation TEXT,
    city TEXT,
    state TEXT,
    phone TEXT,
    email TEXT,
    initial_contact DATE,
    studies TEXT,
    veteran BOOLEAN,
    tag_number INTEGER
);
--- Medical History Table
CREATE TABLE medical_history (
    id INTEGER PRIMARY KEY,
    donor_id INTEGER NOT NULL,
    joint_replacement BOOLEAN,
    joint_replacement_age INTEGER,
    joints TEXT,
    heart_surgery BOOLEAN,
    heart_surgery_age INTEGER,
    spine_surgery BOOLEAN,
    spine_surgery_age INTEGER,
    gall_bladder_removed BOOLEAN,
    gall_bladder_removed_age INTEGER,
    appendix_removed BOOLEAN,
    appendix_removed_age INTEGER,
    tonsils_removed BOOLEAN,
    tonsils_removed_age INTEGER,
    num_pregnancies INTEGER,
    hysterectomy BOOLEAN,
    hysterectomy_age INTEGER,
    cesarean_section BOOLEAN,
    cesarean_section_age INTEGER,
    other_surgeries TEXT,
    cancer_history_treatment TEXT,
    illnesses TEXT,
    injuries TEXT,
    cadaver_utilization TEXT,
    additional_notes TEXT,
    FOREIGN KEY (donor_id) REFERENCES donors(id)
);
-- Relationship Table
CREATE TABLE relationships (
    id INTEGER PRIMARY KEY,
    relationship_name TEXT NOT NULL
);
--- NOOK Table 
CREATE TABLE next_of_kin (
    id INTEGER PRIMARY KEY,
    donor_id INTEGER NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    relationship_id INTEGER,
    address1 TEXT,
    address2 TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    phone TEXT,
    email TEXT,
    primary_nok BOOLEAN,
    conversation_log TEXT,
    additional_notes TEXT,
    FOREIGN KEY (donor_id) REFERENCES donors(id),
    FOREIGN KEY (relationship_id) REFERENCES relationships(id)
);
-- Funeral Homes Table
CREATE TABLE funeral_homes (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    address1 TEXT,
    address2 TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    phone TEXT,
    fax TEXT,
    email TEXT,
    conversation_log TEXT,
    additional_notes TEXT,
    review BOOLEAN,
    archive BOOLEAN
);
-- Embalming Table
CREATE TABLE embalming (
    id INTEGER PRIMARY KEY,
    donor_id INTEGER NOT NULL,
    funeral_home_id INTEGER,
    morgue_location TEXT,
    memorial_service BOOLEAN,
    body_present_at_service BOOLEAN,
    pickup_time TEXT,
    initial_embalming BOOLEAN,
    funeral_home_embalming_condition TEXT,
    start_date DATE,
    end_date DATE,
    photo_upon_arrival BOOLEAN,
    condition_on_arrival TEXT,
    condition_after_embalming TEXT,
    fluid_amount REAL,
    r_carotid BOOLEAN,
    l_carotid BOOLEAN,
    r_femoral BOOLEAN,
    l_femoral BOOLEAN,
    point_injections BOOLEAN,
    brain_embalmed BOOLEAN,
    head_shaved BOOLEAN,
    appendages_bagged BOOLEAN,
    disinfectant_wash BOOLEAN,
    additional_sites TEXT,
    cavity_work_aspiration BOOLEAN,
    ssom_arrival_date DATE,
    photo_after_embalming BOOLEAN,
    embalming_notes TEXT,
    return_ashes BOOLEAN,
    return_ashes_to TEXT,
    transport BOOLEAN,
    transport_method TEXT,
    miles INTEGER,
    bill_to TEXT,
    thank_you_sent BOOLEAN,
    invoice_sent BOOLEAN,
    contact_person TEXT,
    FOREIGN KEY (donor_id) REFERENCES donors(id),
    FOREIGN KEY (funeral_home_id) REFERENCES funeral_homes(id)
);
